name = "vectum"
version = "0.1.0"
description = "A lightweight, self-hosted event router for cloud, on-prem, and edge environments"
licences = ["Apache-2.0"]
gleam = ">= 1.18.0"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
